Sscs 9025 automation tests
hmcts/sscs-submit-your-appeal pull request #1271
Opened 2022-01-06 14:55 UTC by TeaWithLucas

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/SSCS-9025

### Change description ###
Adding the tags so that the following are run with nightly tests:
- https://github.com/hmcts/sscs-submit-your-appeal/blob/master/test/e2e/journeys/noMRN.en.test.js
- https://github.com/hmcts/sscs-submit-your-appeal/blob/master/test/e2e/journeys/mrnLate.en.test.js
Adding new logic to allow calling the Tribual Case API and getting case data
Creating a new test (for both en and cy) to test the status of the case on CCD when a draft is submitted when signed in

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-01-06 16:23 UTC, rasikasri approved these changes

2022-01-10 12:55 UTC, dattipoeHMCTS commented on test/e2e/page-objects/tribunals-case-api/getCaseData.js
> +    throw Error('Invalid API Response)');
'Invalid API Response appeal is missing from returned data' would be better - you always want to make whoever has to sift through log's life easier.

2022-01-10 12:56 UTC, dattipoeHMCTS commented on test/e2e/page-objects/tribunals-case-api/getCaseData.js
> +    throw Error(`HTTP Error ${status} not correct`);
..is invalid reads better

2022-01-10 12:58 UTC, dattipoeHMCTS commented on test/e2e/page-objects/tribunals-case-api/getCaseData.js
> +    throw Error('Invalid API Response)');
Same as above.

You could actually extract this whole block into a common function and pass in different functions for what to return. The only difference is:

if (res.data && res.data.appeal) {
      return res.data.appeal;
    }
    
and

if (res.data) {
      return res.data;
    }

2022-01-10 13:00 UTC, dattipoeHMCTS commented on test/e2e/page-objects/tribunals-case-api/getCaseData.js
> +    throw Error('Invalid API Response)');
This would mean you can cut the number of tests in ~half too

2022-01-12 11:02 UTC, ss-evoco approved these changes

2022-01-12 11:05 UTC, dattipoeHMCTS approved these changes

2022-01-17 13:54 UTC, gokul-sol requested changes

2022-01-17 13:54 UTC, gokul-sol commented on test/e2e/page-objects/identity/appellantDetails.js
> +function enterAppellantContactDetailsAndContinueAfterSignIn(commonContent, language) {
Again original method is here https://github.com/hmcts/sscs-submit-your-appeal/blob/4f7ace0242ee6c81d5d5e2f2ef421cf8f2e7a70b/test/e2e/page-objects/identity/appellantDetails.js#L96

don't need this duplicate method

2022-01-26 11:08 UTC, bensonlievoco commented on test/e2e/page-objects/sign-in/sign-in-with-valid-creds.js
> +async function signInVerifylanguage(username, password, language) {
for above duplicate method, we can create another ticket to modify it, since similar case appear elsewhere

2022-01-28 15:13 UTC, closed without merging