SSCS-10486: Update SYA contact opening hours
hmcts/sscs-submit-your-appeal pull request #1320
Opened 2022-05-06 12:17 UTC by Jonathan-Weston1

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/SSCS-10486

### Change description ###
Update contact us opening hours. Removal of Saturday opening hours and change to monday - Friday

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2022-05-09 09:44 UTC, MohammedHMCTS approved these changes

2022-05-09 10:43 UTC, dattipoeHMCTS approved these changes

2022-05-09 16:54 UTC, TeaWithLucas requested changes
Don't you need to change the welsh too?
https://github.com/hmcts/sscs-submit-your-appeal/blob/SSCS-10486/steps/policy-pages/accessibility/content.cy.json
"availability": "Dydd Llun i ddydd Gwener, 8am i 5pm",

2022-05-10 13:02 UTC, TeaWithLucas approved these changes

2022-05-25 16:03 UTC, merged