SSCSCI-699
hmcts/sscs-submit-your-appeal pull request #1482
Opened 2024-04-19 09:36 UTC by hashimalisolirius

### Jira link (if applicable)

https://tools.hmcts.net/jira/browse/SSCSCI-699

### Change description ###

Provide webchat functionality to Scottish users

2024-04-22 12:56 UTC, benouaer commented on assets/js/web-chat.js
> +    if (button !== null && webChat !== null ) {
??

2024-04-22 13:38 UTC, benouaer requested changes
can we separate the script from the button and load it through main.js in globals.html like we do with the main webchat functionality

2024-04-23 14:14 UTC, sanjayparekh-hmcts approved these changes

2024-04-23 14:29 UTC, benouaer approved these changes

2024-04-23 14:33 UTC, hashimalisolirius commented on package.json
> +    "formidable": "^3.5.1"
There's a new security vulnerability for formidable 1.2.2, we're using 3.5.1 but a dependency is using an older version.

2024-07-17 11:10 UTC, merged